# Generated by Django 2.2.13 on 2021-11-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmodel',
            name='unique_model_in_shop',
        ),
    ]
