# Generated by Django 2.2.13 on 2021-11-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211121_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSumm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sum', to='api.Order', verbose_name='Сумма заказа на момент заказа')),
            ],
            options={
                'verbose_name': 'Сумма заказа на момент заказа',
                'verbose_name_plural': 'Суммы заказов на момент заказа',
            },
        ),
    ]
