# Generated by Django 2.2.13 on 2021-11-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordersumm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved_sum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма заказа на момент оплаты'),
        ),
        migrations.DeleteModel(
            name='OrderSumm',
        ),
    ]
